load("@pypi//:requirements.bzl", "requirement")

package(default_visibility = ["//visibility:public"])

py_library(
    name = "electromagnetic_solver",
    srcs = ["electromagnetic_solver.py"],
    deps = [
        "//mesh/py:gmsh_interface",
        "//proto:material_py_proto",
        "//proto:solver_config_py_proto",
        requirement("gmsh"),
        requirement("numpy"),
    ],
)

py_library(
    name = "neighbor_lookup",
    srcs = ["neighbor_lookup.py"],
    deps = [requirement("numpy")],
)
