load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "material",
    srcs = ["material.cc"],
    hdrs = ["material.h"],
    deps = [
        ":constants",
        "//proto:material_cc_proto",
    ],
)

cc_library(
    name = "constants",
    hdrs = ["constants.h"],
)
