load("@pip_deps//:requirements.bzl", "requirement")

package(default_visibility = ["//visibility:public"])

py_library(
    name = "capacitor",
    srcs = ["capacitor.py"],
    deps = ["//proto:capacitor_py_proto"],
)

py_library(
    name = "capacitor_three_plates",
    srcs = ["capacitor_three_plates.py"],
    deps = ["//proto:capacitor_three_plates_py_proto"],
)

py_library(
    name = "material",
    srcs = ["material.py"],
    deps = [
        "//proto:material_py_proto",
        requirement("numpy"),
    ],
)
