module(name = "em-solver")

http_archive = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

bazel_dep(
    name = "abseil-cpp",
    version = "20260107.1",
)
bazel_dep(
    name = "eigen",
    version = "5.0.1",
)
bazel_dep(
    name = "platforms",
    version = "1.0.0",
)
bazel_dep(
    name = "protobuf",
    version = "34.1",
)
bazel_dep(
    name = "rules_cc",
    version = "0.2.17",
)
bazel_dep(
    name = "rules_foreign_cc",
    version = "0.15.1",
)
bazel_dep(
    name = "rules_pkg",
    version = "1.2.0",
)
bazel_dep(
    name = "rules_python",
    version = "1.9.0",
)

# Gmsh library.
GMSH_VERSION = "4.15.2"

http_archive(
    name = "gmsh",
    build_file = "//third_party/gmsh:gmsh.BUILD",
    sha256 = "be3f66f225d27ba9fa014f07e83169285da8a051b0e8ab7103d88066b39bdd3e",
    strip_prefix = "gmsh-{}-source".format(GMSH_VERSION),
    url = "https://gmsh.info/src/gmsh-{}-source.tgz".format(GMSH_VERSION),
)

# OpenBLAS library.
OPENBLAS_VERSION = "0.3.31"

http_archive(
    name = "openblas",
    build_file = "//third_party/openblas:openblas.BUILD",
    sha256 = "6dd2a63ac9d32643b7cc636eab57bf4e57d0ed1fff926dfbc5d3d97f2d2be3a6",
    strip_prefix = "OpenBLAS-{}".format(OPENBLAS_VERSION),
    url = "https://github.com/OpenMathLib/OpenBLAS/archive/refs/tags/v{}.tar.gz".format(OPENBLAS_VERSION),
)

# SuiteSparse library.
SUITESPARSE_VERSION = "7.12.2"

http_archive(
    name = "suitesparse",
    build_file = "//third_party/suitesparse:suitesparse.BUILD",
    patches = ["//third_party/suitesparse:suitesparse.patch"],
    sha256 = "09e7bcc8e5de0a1b55d2ae9fd6378d5f4dc1b85a933593339a0872b24e2cc102",
    strip_prefix = "SuiteSparse-{}".format(SUITESPARSE_VERSION),
    url = "https://github.com/DrTimothyAldenDavis/SuiteSparse/archive/refs/tags/v{}.tar.gz".format(SUITESPARSE_VERSION),
)

# SuperLU library.
SUPERLU_VERSION = "7.0.1"

http_archive(
    name = "superlu",
    build_file = "//third_party/superlu:superlu.BUILD",
    sha256 = "86dcca1e086f8b8079990d07f00eb707fc9ef412cf3b2ce808b37956f0de2cb8",
    strip_prefix = "superlu-{}".format(SUPERLU_VERSION),
    url = "https://github.com/xiaoyeli/superlu/archive/refs/tags/v{}.tar.gz".format(SUPERLU_VERSION),
)

# Configure the Python toolchain.
python = use_extension("@rules_python//python/extensions:python.bzl", "python")
python.toolchain(
    is_default = True,
    python_version = "3.13",
)

# Load pip dependencies.
pip = use_extension("@rules_python//python/extensions:pip.bzl", "pip")
pip.parse(
    hub_name = "pypi",
    python_version = "3.13",
    requirements_lock = "//deps:requirements.txt",
)
use_repo(pip, "pypi")
