load("@pip_deps//:requirements.bzl", "requirement")

package(default_visibility = ["//visibility:public"])

py_library(
    name = "color_maps",
    srcs = ["color_maps.py"],
    deps = [requirement("matplotlib")],
)

py_library(
    name = "electromagnetic_field_plotter",
    srcs = ["electromagnetic_field_plotter.py"],
    deps = [
        ":color_maps",
        "//mesh/py:gmsh_interface",
        requirement("gmsh"),
        requirement("matplotlib"),
        requirement("numpy"),
        requirement("pandas"),
        requirement("SciencePlots"),
    ],
)

py_binary(
    name = "electromagnetic_field_plotter_2d_main",
    srcs = ["electromagnetic_field_plotter_2d_main.py"],
    deps = [
        ":electromagnetic_field_plotter",
        requirement("absl-py"),
    ],
)
