load("@pip_deps//:requirements.bzl", "requirement")
load("@rules_pkg//pkg:tar.bzl", "pkg_tar")

package(default_visibility = ["//visibility:public"])

py_library(
    name = "electrostatic_solver",
    srcs = ["electrostatic_solver.py"],
    deps = [
        "//mesh/py:gmsh_interface",
        "//model:material",
        "//proto:solver_config_py_proto",
        "//solver:electromagnetic_solver",
        "//solver:neighbor_lookup",
        requirement("numpy"),
        requirement("scipy"),
    ],
)

py_library(
    name = "capacitor_electrostatic_solver",
    srcs = ["capacitor_electrostatic_solver.py"],
    deps = [
        ":electrostatic_solver",
        "//mesh/py:gmsh_interface",
        "//model:constants",
        "//model:material",
        "//proto:capacitor_py_proto",
        "//proto:solver_config_py_proto",
        requirement("numpy"),
    ],
)

py_binary(
    name = "capacitor_electrostatic_solver_2d_main",
    srcs = ["capacitor_electrostatic_solver_2d_main.py"],
    data = ["//solver/configs:capacitor_solver_configs"],
    deps = [
        ":capacitor_electrostatic_solver",
        "//proto:solver_config_py_proto",
        "//visualization:electromagnetic_field_plotter",
        requirement("absl-py"),
        requirement("protobuf"),
    ],
)

pkg_tar(
    name = "capacitor_electrostatic_solver_2d_main_tar_pkg",
    srcs = [":capacitor_electrostatic_solver_2d_main"],
    extension = ".tar.gz",
    include_runfiles = True,
    strip_prefix = "/solver/electrostatic/",
)

py_library(
    name = "capacitor_three_plates_electrostatic_solver",
    srcs = ["capacitor_three_plates_electrostatic_solver.py"],
    deps = [
        ":electrostatic_solver",
        "//model:material",
        "//proto:capacitor_three_plates_py_proto",
        "//proto:solver_config_py_proto",
    ],
)

py_binary(
    name = "capacitor_three_plates_electrostatic_solver_2d_main",
    srcs = ["capacitor_three_plates_electrostatic_solver_2d_main.py"],
    data = ["//solver/configs:capacitor_solver_configs_three_plates"],
    deps = [
        ":capacitor_three_plates_electrostatic_solver",
        "//proto:solver_config_py_proto",
        "//visualization:electromagnetic_field_plotter",
        requirement("absl-py"),
        requirement("protobuf"),
    ],
)

pkg_tar(
    name = "capacitor_three_plates_electrostatic_solver_2d_main_tar_pkg",
    srcs = [":capacitor_three_plates_electrostatic_solver_2d_main"],
    extension = ".tar.gz",
    include_runfiles = True,
    strip_prefix = "/solver/electrostatic/",
)
