package(default_visibility = ["//visibility:public"])

cc_library(
    name = "capacitor_electrostatic_solver",
    srcs = ["capacitor_electrostatic_solver.cc"],
    hdrs = ["capacitor_electrostatic_solver.h"],
    deps = [
        ":electrostatic_solver",
        "//model:material",
        "//proto:capacitor_cc_proto",
        "//proto:solver_config_cc_proto",
        "@abseil-cpp//absl/strings:str_format",
    ],
)

cc_binary(
    name = "capacitor_electrostatic_solver_2d_main",
    srcs = ["capacitor_electrostatic_solver_2d_main.cc"],
    deps = [
        ":capacitor_electrostatic_solver",
        "//base",
        "//base:commandlineflags",
        "@com_google_protobuf//:protobuf",
    ],
)

cc_library(
    name = "electrostatic_solver",
    srcs = ["electrostatic_solver.cc"],
    hdrs = ["electrostatic_solver.h"],
    deps = [
        "//mesh:gmsh_interface",
        "//model:material",
        "//proto:solver_config_cc_proto",
        "//solver:electromagnetic_solver",
        "//solver:neighbor_lookup",
        "@abseil-cpp//absl/strings:str_format",
        "@eigen",
        "@suitesparse//:umfpack",
    ],
)
