load("@protobuf//bazel:cc_proto_library.bzl", "cc_proto_library")
load("@protobuf//bazel:proto_library.bzl", "proto_library")
load("@protobuf//bazel:py_proto_library.bzl", "py_proto_library")

package(default_visibility = ["//visibility:public"])

proto_library(
    name = "capacitor_proto",
    srcs = ["capacitor.proto"],
)

cc_proto_library(
    name = "capacitor_cc_proto",
    deps = [":capacitor_proto"],
)

py_proto_library(
    name = "capacitor_py_proto",
    deps = [":capacitor_proto"],
)

proto_library(
    name = "capacitor_three_plates_proto",
    srcs = ["capacitor_three_plates.proto"],
)

cc_proto_library(
    name = "capacitor_three_plates_cc_proto",
    deps = [":capacitor_three_plates_proto"],
)

py_proto_library(
    name = "capacitor_three_plates_py_proto",
    deps = [":capacitor_three_plates_proto"],
)

proto_library(
    name = "complex_number_proto",
    srcs = ["complex_number.proto"],
)

proto_library(
    name = "material_proto",
    srcs = ["material.proto"],
)

cc_proto_library(
    name = "material_cc_proto",
    deps = [":material_proto"],
)

py_proto_library(
    name = "material_py_proto",
    deps = [":material_proto"],
)

proto_library(
    name = "mesh_config_proto",
    srcs = ["mesh_config.proto"],
    deps = [":material_proto"],
)

cc_proto_library(
    name = "mesh_config_cc_proto",
    deps = [":mesh_config_proto"],
)

py_proto_library(
    name = "mesh_config_py_proto",
    deps = [":mesh_config_proto"],
)

proto_library(
    name = "solver_config_proto",
    srcs = ["solver_config.proto"],
    deps = [":complex_number_proto"],
)

cc_proto_library(
    name = "solver_config_cc_proto",
    deps = [":solver_config_proto"],
)

py_proto_library(
    name = "solver_config_py_proto",
    deps = [":solver_config_proto"],
)
