syntax = "proto3";

package mesh;

import "proto/material.proto";

// Mesh generator configuration.
message MeshGeneratorConfig {
  // Minimum element size factor.
  double lc_min_factor = 1;

  // Maximum element size factor.
  double lc_max_factor = 2;

  // Distance up to which the element size is minimal.
  double distance_min_factor = 3;

  // Distance after which the element size is maximal.
  double distance_max_factor = 4;
}

// Entity configuration.
message EntityConfig {
  // Entity tag.
  int32 tag = 1;

  // Entity material.
  model.Material material = 2;
}

// Mesh configuration.
message MeshConfig {
  // Generator configuration.
  MeshGeneratorConfig generator_config = 1;

  // Entity configurations.
  repeated EntityConfig entity_configs = 2;
}
