load("@pip_deps//:requirements.bzl", "requirement")

package(default_visibility = ["//visibility:public"])

py_library(
    name = "constants",
    srcs = ["constants.py"],
)

py_library(
    name = "electromagnetic_solver",
    srcs = ["electromagnetic_solver.py"],
    deps = [
        "//mesh:gmsh_interface",
        "//proto:material_py_proto",
        "//proto:solver_config_py_proto",
        "//visualization:color_maps",
        requirement("gmsh"),
        requirement("matplotlib"),
        requirement("numpy"),
        requirement("SciencePlots"),
    ],
)

py_library(
    name = "neighbor_lookup",
    srcs = ["neighbor_lookup.py"],
    deps = [requirement("numpy")],
)
